name: Core.Testing.NUnit

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Core/Testing.NUnit/**/*
jobs:
  full-release:
    uses: ./.github/workflows/full-release.yml
    secrets: inherit
    with:
      path: Core/Testing.NUnit
      name: 'Sugar.Core.Testing.NUnit'
