name: full-release

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      config:
        required: false
        default: 'Release'
        type: string
      path:
        required: true
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      config:
        required: false
        default: 'Release'
        type: string
      path:
        required: true
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
jobs:
  build:
    uses: ./.github/workflows/build-dotnet.yml
    with:
      name: ${{ inputs.name }}
      config: ${{ inputs.config }}
      path: ${{ inputs.path }}
  release:
    uses: ./.github/workflows/nuget-release.yml
    secrets: inherit 
    needs: build