name: nuget-release

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Push
        run: dotnet nuget push ./${{ inputs.name }}/*.*nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}