name: publish-common-sdk

env:
  path: Project.Sdks/Common
  workflows: ./.github/workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - $path/**/*

jobs:
  build:
    uses: $workflows/build-dotnet.yml@main
    with:
      config: 'Release'
      path: $path
  release:
    uses: $workflows/nuget-release.yml@main
    secrets: inherit 
    needs: build