name: publish-common-sdk

env:
  path: Project.Sdks/Common

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - $path/**/*

jobs:
  build:
    uses: ./.github/workflows/build-dotnet.yml
    with:
      config: 'Release'
      path: $path
  release:
    uses: ./.github/workflows/nuget-release.yml
    secrets: inherit 
    needs: build