name: publish-common-sdk

env:
  path: Project.Sdks/Common

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - $path/**/*

jobs:
  build:
    uses: ./build-dotnet.yml@main
    with:
      config: 'Release'
      path: $path
  release:
    uses: ./nuget-release.yml@main
    secrets: inherit 
    needs: build